basic_info/urls.py
from django.urls import path
from basic_info import views

app_name = 'basic_info'

urlpatterns = [
    path('zt/', views.zt, name='zt'),
    path('cx/', views.cx, name='cx'),
    path('yz/', views.yz, name='yz'),
    path('bs/', views.bs, name='bs'),
    path('gxr/', views.gxr, name='gxr'),
    path('ypjl/', views.ypjl, name='ypjl'),
    path('sfyj/', views.sfyj, name='sfyj'),
    path('sw/', views.sw, name='sw'),
    path('jt/', views.jt, name='jt'),
    path('dt/', views.dt, name='dt'),
    path('ypbg/', views.ypbg, name='ypbg'),
    path('add_ypbg/', views.add_ypbg, name='add_ypbg'),
    path('ypzg/', views.ypzg, name='ypzg'),
    path('zhzg/', views.zhzg, name='zhzg'),
    path('zgtj/', views.zgtj, name='zgtj'),
    path('ypdb/', views.ypdb, name='ypdb'),
    path('attention/', views.attention, name='attention'),
    path('gz_cancel/<str:pk>/', views.gz_cancel, name='gz_cancel'),
    path('add_attention/<str:pk>/', views.add_attention, name='add_attention'),
    path('cancel_attention/<str:pk>/', views.cancel_attention, name='cancel_attention'),
    path('details/<str:pk>/', views.details, name='details'),
    path('basic_details/<str:pk>/', views.basic_details, name='basic_details'),
    path('gxr_details/<str:pk>/', views.gxr_details, name='gxr_details'),
    path('ypjl_details/<str:pk>/', views.ypjl_details, name='ypjl_details'),
    path('add_ypjl/<str:pk>/', views.add_ypjl, name='add_ypjl'),
    path('view_ypjl/<str:pk>/', views.view_ypjl, name='view_ypjl'),
    path('sfyj_details/<str:pk>/', views.sfyj_details, name='sfyj_details'),
    path('sw_details/<str:pk>/', views.sw_image_details, name='sw_image_details'),
    path('jt_details/<str:pk>/', views.jt_image_details, name='jt_image_details'),
    path('dt_details/<str:pk>/', views.dt_image_details, name='dt_image_details'),
    path('update_sw_cz/', views.update_sw_cz, name='update_sw_cz'),
    path('update_jt_cz/', views.update_jt_cz, name='update_jt_cz'),
    path('update_dt_cz/', views.update_dt_cz, name='update_dt_cz'),
    path('update_basic_zt/', views.update_basic_zt, name='update_basic_zt'),
    path('zt_filter/', views.zt_filter, name='zt_filter'),
    path('yz_filter/', views.yz_filter, name='yz_filter'),
    path('bs_filter/', views.bs_filter, name='bs_filter'),
    path('cx_filter/', views.cx_filter, name='cx_filter'),

]

ztry/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from basic_info import views as basic_info_views
urlpatterns = [
    path('home/', basic_info_views.home, name='home'),
    path('admin/', admin.site.urls, name='admin'),
    path('info/', include('basic_info.urls',)),
    path('', include('login.urls',)),

]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basic_info/models.py
from datetime import timedelta
from django.db import models
from login.models import CustomUser


def swzp_image_upload_path(instance, filename):
    # 使用 instance.basic_info.ztrybh 来动态生成路径
    return f'image/sw_images/{instance.ztrybh}/{filename}'
def jtbd_image_upload_path(instance, filename):
    # 使用 instance.basic_info.ztrybh 来动态生成路径
    return f'image/jt_images/{instance.ztrybh}/{filename}'
def dtbd_image_upload_path(instance, filename):
    # 使用 instance.basic_info.ztrybh 来动态生成路径
    return f'image/dt_images/{instance.ztrybh}/{filename}'
def yp_image_upload_path(instance, filename):
    # 使用 instance.basic_info.ztrybh 来动态生成路径
    return f'image/yp_images/{instance.ztrybh}/{filename}'

class BasicInfo(models.Model):
    id = models.AutoField(primary_key=True)
    ztrybh = models.CharField(max_length=50, verbose_name="在逃人员编号",db_index=True)
    name = models.CharField(max_length=50, verbose_name="姓名",blank=True,null=True)
    id_card = models.CharField(max_length=50, verbose_name="身份证号码",blank=True,null=True)
    hjdz = models.CharField(max_length=100, verbose_name="户籍地址",blank=True,null=True)
    ajlb = models.CharField(max_length=50, verbose_name="案件类别",blank=True,null=True)
    jyaq = models.CharField(max_length=5000, verbose_name="简要案情",blank=True,null=True)
    swdw = models.CharField(max_length=50, verbose_name="上网单位",blank=True,null=True)
    swsj = models.DateTimeField(verbose_name="上网时间",blank=True,null=True)
    xxzjbh = models.CharField(max_length=50, verbose_name="信息主键编号", blank=True, null=True)
    zt = models.CharField(max_length=50, verbose_name="状态", default='在逃',blank=True,null=True,choices=[("在逃", "在逃"),("已抓获", "已抓获")])
    bssw = models.CharField( max_length=50,verbose_name="本市上网",blank=True,null=True)
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    updated_by = models.CharField(max_length=50, verbose_name="更新人", blank=True,null=True)
    update_at =models.DateTimeField(verbose_name="更新时间",auto_now=True)

    class Meta:
        verbose_name = '在逃人员信息'
        verbose_name_plural = verbose_name
        indexes=[
            models.Index(fields=['ztrybh']),
        ]

    def save(self,*args, **kwargs):
        if self.swdw is None or not any(city in (self.swdw or '') for city in ["无锡市公安局", "江阴市公安局", "宜兴市公安局"]):
            self.bssw="否"
        else:
            self.bssw="是"
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.ztrybh}"

class Backout(models.Model):
    id = models.AutoField(primary_key=True)
    ztrybh = models.CharField(max_length=50, verbose_name="在逃人员编号",db_index=True)
    name = models.CharField(max_length=50, verbose_name="姓名",blank=True,null=True)
    id_card = models.CharField(max_length=50, verbose_name="身份证号码",blank=True,null=True)
    ajlb = models.CharField(max_length=50, verbose_name="案件类别",blank=True,null=True)
    swdw = models.CharField(max_length=50, verbose_name="上网单位",blank=True,null=True)
    swsj = models.DateTimeField(verbose_name="上网时间",blank=True,null=True)
    zhdw = models.CharField(max_length=50, verbose_name="抓获单位",blank=True,null=True)
    cxsj = models.DateTimeField(verbose_name="撤销时间",blank=True,null=True)
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    class Meta:
        verbose_name = '在逃人员信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return f"{self.ztrybh}"

class Ypjl(models.Model):
    id = models.AutoField(primary_key=True)
    ztrybh = models.CharField(max_length=50, verbose_name="在逃人员编号",db_index=True)
    ypnr = models.TextField( verbose_name="研判记录",blank=True,null=True)
    yptp = models.ImageField(upload_to=yp_image_upload_path, verbose_name="研判记录图片", max_length=255,blank=True, null=True)
    ypr = models.CharField(max_length=50, verbose_name="研判人")
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    updated_by = models.CharField(max_length=50, verbose_name="更新人", blank=True, null=True)
    update_at = models.DateTimeField(verbose_name="更新时间", auto_now=True)

    class Meta:
        verbose_name = '研判记录'
        verbose_name_plural = verbose_name
        indexes = [
            models.Index(fields=['ztrybh']),
        ]

    def __str__(self):
        return f"{self.ztrybh}"

class SwImage(models.Model):
    id = models.AutoField(primary_key=True)
    ztrybh = models.CharField(max_length=50, verbose_name="在逃人员编号",db_index=True)
    swzp = models.ImageField(upload_to=swzp_image_upload_path, verbose_name="上网图片", max_length=255,blank=True,null=True)
    cz = models.CharField(max_length=50, verbose_name="处置", choices=[("本人","本人"),("非本人","非本人")],default="本人")
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    updated_by = models.CharField(max_length=50, verbose_name="更新人", blank=True, null=True)
    update_at =models.DateTimeField(verbose_name="更新时间",auto_now=True)

    class Meta:
        verbose_name = '上网图片'
        verbose_name_plural = verbose_name
        indexes = [
            models.Index(fields=['ztrybh']),
        ]

    def __str__(self):
        return f"{self.ztrybh}"

class JtImage(models.Model):
    id = models.AutoField(primary_key=True)
    ztrybh = models.CharField(max_length=50, verbose_name="在逃人员编号",db_index=True)
    jtbd = models.ImageField(upload_to=jtbd_image_upload_path, verbose_name="静态比对图片", max_length=255,blank=True,null=True)
    cz = models.CharField(max_length=50, verbose_name="处置", blank=True,choices=[("排除","排除"),("已抓获","已抓获"),("确认","确认")],default="确认")
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    updated_by = models.CharField(max_length=50, verbose_name="更新人", blank=True, null=True)
    update_at =models.DateTimeField(verbose_name="更新时间",auto_now=True)

    class Meta:
        verbose_name = '静态比对图片'
        verbose_name_plural = verbose_name
        indexes = [
            models.Index(fields=['ztrybh']),
        ]

    def __str__(self):
        return f"{self.ztrybh}"

class DtImage(models.Model):
    id = models.AutoField(primary_key=True)
    ztrybh = models.CharField(max_length=50, verbose_name="在逃人员编号",db_index=True)
    dtbd = models.ImageField(upload_to=dtbd_image_upload_path, verbose_name="动态比对图片", max_length=255,blank=True,null=True)
    cz = models.CharField(max_length=50, verbose_name="处置", blank=True,choices=[("排除","排除"),("已抓获","已抓获"),("确认","确认")],default="确认")
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    updated_by = models.CharField(max_length=50, verbose_name="更新人", blank=True, null=True)
    update_at =models.DateTimeField(verbose_name="更新时间",auto_now=True)

    class Meta:
        verbose_name = '动态比对图片'
        verbose_name_plural = verbose_name
        indexes = [
            models.Index(fields=['ztrybh']),
        ]

    def __str__(self):
        return f"{self.ztrybh}"


class Sfyj(models.Model):
    id = models.AutoField(primary_key=True)
    ztrybh = models.CharField(max_length=50, verbose_name="在逃人员编号",db_index=True)
    swsj = models.DateField(verbose_name="上网日期", blank=True, null=True)
    name = models.CharField(max_length=50, verbose_name="姓名", blank=True,null=True)
    id_card = models.CharField(max_length=20, verbose_name="身份证号码",blank=True,null=True)
    hdsj = models.DateTimeField(verbose_name="活动时间",blank=True, null=True)
    sjly = models.CharField(max_length=50, verbose_name="数据来源", blank=True,null=True)
    yjxx = models.CharField(max_length=5000, verbose_name="预警信息",blank=True,null=True)
    cz = models.CharField(max_length=50, verbose_name="处置",blank=True,null=True)
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    updated_by = models.CharField(max_length=50, verbose_name="更新人", blank=True, null=True)
    update_at =models.DateTimeField(verbose_name="更新时间",auto_now=True)

    class Meta:
        verbose_name = '身份信息预警'
        verbose_name_plural = verbose_name
        indexes = [
            models.Index(fields=['ztrybh']),
        ]

    def __str__(self):
        return f"{self.ztrybh}"

class Ypbg(models.Model):
    id = models.AutoField(primary_key=True)
    ztrybh = models.CharField(max_length=50, verbose_name="在逃人员编号",db_index=True)
    name = models.CharField(max_length=50, verbose_name="姓名", blank=True,null=True)
    id_card = models.CharField(max_length=20, verbose_name="身份证号码",blank=True,null=True)
    swdw = models.CharField(max_length=50, verbose_name="上网单位", blank=True,null=True)
    swsj = models.DateTimeField(verbose_name="上网时间", blank=True, null=True)
    sbdw = models.CharField(max_length=50, verbose_name="上报单位", blank=True,null=True)
    sbsj = models.DateTimeField(verbose_name="上报时间",blank=True, null=True)
    dqsj = models.DateTimeField(verbose_name="到期时间",blank=True, null=True)
    zhdw = models.CharField(max_length=50, verbose_name="抓获单位", blank=True, null=True)
    zhsj = models.DateTimeField(verbose_name="抓获时间",blank=True, null=True)
    cxsj = models.DateTimeField(verbose_name="撤销时间", blank=True, null=True)
    xsfw = models.CharField(max_length=50, verbose_name="线索范围", blank=True,null=True)
    fz = models.CharField(max_length=50, verbose_name="分值", blank=True,null=True)
    zg = models.CharField(max_length=50, verbose_name="战果认定", blank=True,null=True)
    create_at = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    updated_by = models.CharField(max_length=50, verbose_name="更新人", blank=True, null=True)
    update_at =models.DateTimeField(verbose_name="更新时间",auto_now=True)

    class Meta:
        verbose_name = '研判报告'
        verbose_name_plural = verbose_name
        indexes = [
            models.Index(fields=['ztrybh']),
        ]

    def save(self, *args, **kwargs):
        if self.sbsj:
            self.dqsj = self.sbsj + timedelta(days=60)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.ztrybh}"

class Zhzg(models.Model):
    id = models.AutoField(primary_key=True)

basic_info/forms.py
from django import forms
from .models import Ypbg,Ypjl

class YpbgForm(forms.ModelForm):
    class Meta:
        model = Ypbg
        fields = ['ztrybh','swsj','name','id_card','swdw','sbsj','fz','zg']
        widgets = {
            'swsj': forms.DateInput(attrs={'type': 'datetime-local'}),
            'sbsj': forms.DateInput(attrs={'type': 'datetime-local'}),
        }

class ZtQueryForm(forms.Form):
    ztrybh = forms.CharField(required=False, label="在逃人员编号")
    name = forms.CharField(required=False, label="姓名")
    id_card = forms.CharField(required=False, label="身份证号码")
    ajlb = forms.CharField(required=False, label="案件类别")
    swdw = forms.CharField(required=False, label="上网单位")
    swsj = forms.CharField(required=False, label="上网日期")

class YzQueryForm(forms.Form):
    ztrybh = forms.CharField(required=False, label="在逃人员编号")
    name = forms.CharField(required=False, label="姓名")
    id_card = forms.CharField(required=False, label="身份证号码")
    ajlb = forms.CharField(required=False, label="案件类别")
    swdw = forms.CharField(required=False, label="上网单位")
    swsj = forms.CharField(required=False, label="上网日期")

class BsQueryForm(forms.Form):
    ztrybh = forms.CharField(required=False, label="在逃人员编号")
    name = forms.CharField(required=False, label="姓名")
    id_card = forms.CharField(required=False, label="身份证号码")
    ajlb = forms.CharField(required=False, label="案件类别")
    swdw = forms.CharField(required=False, label="上网单位")
    swsj = forms.CharField(required=False, label="上网日期")

class YpjlForm(forms.ModelForm):
    class Meta:
        model = Ypjl
        fields = ['ztrybh', 'ypnr', 'ypr']
        widgets = {
            'ypnr': forms.Textarea(attrs={'rows': 4, 'placeholder': '请输入研判内容'}),
        }

basic_info/templates/add_ypbg.html
{% extends "text_base.html" %}
{% block title %}添加研判报告{% endblock %}
{% block subtitle %}添加研判报告信息{% endblock %}
{% block content %}
    <form method="post" class="form-container">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit_button">提交</button>
    </form>
{% endblock %}
{% block pagination %}{% endblock %}

basic_info/templates/add_ypjl.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加研判记录</title>
    <style>
        body {
            font-family: Arial, sans-serif; /* 设置字体 */
            background-color: #f4f4f4; /* 背景颜色 */
            margin: 0;
            padding: 20px;
        }
        .header {
            background-color: #4c78ad; /* 顶部背景色 */
            color: white;
            text-align: center;
            padding: 20px;
        }
        .header h1 {
            font-size: 60px; /* 系统名称字体大小 */
            margin: 0;
        }
        .subtitle {
            text-align: center;
            font-size: 24px; /* 副标题字体大小 */
            margin: 10px 0 0; /* 副标题与系统名称间距 */
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            background-color: #fff; /* 表格背景颜色 */
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1); /* 添加阴影效果 */
        }
        th, td {
            border: 1px solid #ddd;
            padding: 10px; /* 增加内边距 */
            text-align: center;
            font-size: 16px;
        }
        th {
            background-color: #4c78ad; /* 表头背景颜色 */
            color: white;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9; /* 偶数行背景颜色 */
        }
        tr:hover {
            background-color: #f1f1f1; /* 鼠标悬停效果 */
        }
        .pagination {
            margin-top: 20px;
            text-align: right;
        }
        .pagination a {
            margin-left: 10px;
            padding: 5px 10px;
            border: 1px solid #ddd;
            background-color: #f7f7f7;
            color: #333;
            text-decoration: none;
            border-radius: 4px;
            transition: background-color 0.3s; /* 添加过渡效果 */
        }
        .pagination a:hover {
            background-color: #e9e9e9; /* 鼠标悬停效果 */
        }
        .form-container input[type="text"]{
            width: 100%; /* 输入框宽度占满整个表单组宽度 */
            padding: 8px;
            border: 1px solid #ddd;
            border-radius: 5px;
            box-sizing: border-box;
        }
        .form-container input[type="submit"] {
            padding: 10px 10px;
            border: none;
            border-radius: 5px;
            background-color: #5cb85c;
            color: white;
            font-size: 15px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            grid-column: span 2; /* 提交按钮横跨两列 */
            margin-top: 10px;
        }
        .form-container input[type="submit"]:hover {
            background-color: #4cae4c;
        }

        /* 按钮样式 */
        .add-button {
            display: inline-block;
            padding: 12px 20px; /* 增加按钮内边距 */
            font-size: 16px; /* 增加字体大小 */
            background-color: #007bff; /* 按钮背景颜色 */
            color: white; /* 按钮文本颜色 */
            text-decoration: none; /* 去掉下划线 */
            border-radius: 5px; /* 按钮圆角 */
            transition: background-color 0.3s; /* 背景颜色变化过渡 */
            margin-bottom: 20px; /* 按钮与输入框间距 */
        }

        .add-button:hover {
            background-color: #0056b3; /* 悬停时的背景颜色 */
        }
        .button-container {
            text-align: center;
        }
        textarea {
            width: 50%; /* 文本框宽度100% */
            height: 450px; /* 文本框高度 */
            padding: 10px; /* 内边距 */
            font-size: 16px; /* 字体大小 */
            border: 1px solid #ccc; /* 边框 */
            border-radius: 5px; /* 圆角 */
            margin-bottom: 20px; /* 与其他元素间距 */
            resize: vertical; /* 允许垂直调整大小 */
        }
        input[type="file"] {
            margin-bottom: 20px; /* 与其他元素间距 */
        }
        textarea:focus {
            border-color: #007bff; /* 聚焦时的边框颜色 */
            box-shadow: 0 0 8px rgba(0, 123, 255, 0.5); /* 聚焦时的阴影效果 */
            outline: none; /* 移除默认的聚焦轮廓 */
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>在逃人员综合研判平台</h1>
    </div>
    <div class ='subtitle' >
        <h2>添加研判记录</h2>
    </div>
    <div class="button-container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="ypnr">研判内容:</label><br><br>
        <textarea id="ypnr" name="ypnr" required ></textarea><br>
        <label for="image">上传图片:</label>
        <input type="file" id="yptp" name="yptp" accept="image/*">
        {{ form.ypnr|safe }}
        <button type="submit" class="add-button">提交</button>
    </form>
    </div>
</body>
</html>

basic_info/templates/attention.html
{% extends "basic_base.html" %}

{% block title %}关注在逃{% endblock %}
{% block subtitle %}关注在逃人员信息{% endblock %}

{% block table_content %}
<table>
    <thead>
        <tr>
            <th>序号</th>
            <th>在逃人员编号</th>
            <th>姓名</th>
            <th>身份证号码</th>
            <th>户籍地址</th>
            <th>案件类别</th>
            <th>上网单位</th>
            <th>上网时间</th>
            <th>状态</th>
            <th>详情</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in page_obj %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ obj.ztrybh }}</td>
                <td>{{ obj.basic_info.name }}</td>
                <td>{{ obj.basic_info.id_card }}</td>
                <td>{{ obj.basic_info.hjdz }}</td>
                <td>{{ obj.basic_info.ajlb }}</td>
                <td>{{ obj.basic_info.swdw }}</td>
                <td>{{ obj.basic_info.swsj|date:"Y-m-d" }}</td>
                <td>{{ obj.basic_info.zt }}</td>
                <td><a href="{% url 'basic_info:details' pk=obj.pk %}" target="_blank">查看</a></td>
                <td>
                    <form action="{% url 'basic_info:gz_cancel' obj.id %}" method="post">
                        {% csrf_token %}
                        <button class="cancel-follow" type="submit">取消关注</button>
                    </form>
                </td>
            </tr>
        {% empty %}
        <tr>
            <td colspan="14">没有找到结果。</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

basic_info/templates/basic_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}系统名称{% endblock %}</title>
    {% block style_content %}
    <style>
        body {
            font-family: Arial, sans-serif; /* 设置字体 */
            background-color: #f4f4f4; /* 背景颜色 */
            margin: 0;
            padding: 20px;
        }
        .header {
            background-color: #4c78ad; /* 顶部背景色 */
            color: white;
            text-align: center;
            padding: 20px;
        }
        .header h1 {
            font-size: 60px; /* 系统名称字体大小 */
            margin: 0;
        }
        .subtitle {
            text-align: center;
            font-size: 24px; /* 副标题字体大小 */
            margin: 10px 0 0; /* 副标题与系统名称间距 */
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            background-color: #fff; /* 表格背景颜色 */
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1); /* 添加阴影效果 */
        }
        th, td {
            border: 1px solid #ddd;
            padding: 5px; /* 增加内边距 */
            text-align: center;
            font-size: 14px;
        }
        th {
            background-color: #4c78ad; /* 表头背景颜色 */
            color: white;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9; /* 偶数行背景颜色 */
        }
        tr:hover {
            background-color: #f1f1f1; /* 鼠标悬停效果 */
        }
        .pagination {
            position: fixed;
            bottom: 20px;
            right: 20px;
            text-align: center;
            z-index: 100;
        }

        .pagination a {
            margin: 0 5px;
            padding: 5px 10px;
            border: 1px solid #ddd;
            background-color: #f7f7f7;
            color: #333;
            text-decoration: none;
            border-radius: 4px;
            transition: background-color 0.3s ease, transform 0.2s ease;
        }

        .pagination a:hover {
            background-color: #e9e9e9;
            transform: scale(1.05); /* 按钮放大效果 */
        }

        .pagination a.active {
            background-color: #4CAF50;
            color: white;
        }

        .pagination a.disabled {
            background-color: #f0f0f0;
            color: #ccc;
            pointer-events: none;
        }

        img {
            max-width: 50px; /* 设置图片的最大宽度 */
            max-height: 50px; /* 设置图片的最大高度 */
            object-fit: cover; /* 保持图片的比例 */
            border-radius: 5px; /* 圆角效果 */
        }
        button {
            padding: 8px 13px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 13px;
            transition: background-color 0.3s, color 0.3s;
        }
        .follow {
            background-color: #007bff; /* 蓝色背景 */
            color: white; /* 白色文字 */
        }

        .follow:hover {
            background-color: #0056b3; /* 深蓝色背景 */
        }

        .cancel-follow {
            background-color: #dc3545; /* 红色背景 */
            color: white; /* 白色文字 */
        }

        .cancel-follow:hover {
            background-color: #c82333; /* 深红色背景 */
        }

        /* 禁用按钮样式 */
        button:disabled {
            background-color: #e9ecef; /* 灰色背景 */
            color: #6c757d; /* 灰色文字 */
            cursor: not-allowed; /* 禁用光标 */
        }
    </style>
    {% endblock %}
</head>
<body>
    <div class="header">
        <h1>在逃人员综合研判平台</h1>
    </div>
    <div class ='subtitle' >
        <h2>{% block subtitle %}{% endblock %}</h2>
    </div>
    {% block table_content %}
    <div class="content">
        <table>
            <thead>
                <tr>
                    <th>序号</th>
                    <th>在逃人员编号</th>
                    <th>上网照片</th>
                    <th>姓名</th>
                    <th>身份证号码</th>
                    <th>户籍地址</th>
                    <th>案件类别</th>
                    <th>上网单位</th>
                    <th>上网时间</th>
                    <th>状态</th>
                    <th>静态比对</th>
                    <th>动态比对</th>
                    <th>研判内容</th>
                    <th>本市上网</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in page_obj %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ obj.ztrybh }}</td>
                        <td>{% if obj.sw_images %}
                                <a href="{% url 'basic_info:sw_image_details' pk=obj.pk %}">
                                    <img src="{{ obj.sw_images.first.swzp.url }}" alt="上网照片">
                                </a>
                            {% else %}
                                无图
                            {% endif %}</td>
                        <td>{{ obj.name }}</td>
                        <td><a href="{% url 'basic_info:sfyj_details' pk=obj.pk %}">{{ obj.id_card }}</a></td>
                        <td>{{ obj.hjdz }}</td>
                        <td>{{ obj.ajlb }}</td>
                        <td>{{ obj.swdw }}</td>
                        <td>{{ obj.swsj|date:"Y-m-d" }}</td>
                        <td>{{ obj.get_zt_display }}</td>
                        <td><a href="{% url 'basic_info:jt_image_details' pk=obj.pk %}">{{ obj.jtbd }}</a></td>
                        <td><a href="{% url 'basic_info:dt_image_details' pk=obj.pk %}">{{ obj.dtbd }}</a></td>
                        <td>{{ obj.yp }}</td>
                        <td>{{ obj.get_bssw_display }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endblock %}
    {% block pagination_content %}
    </div>
        <div class="pagination">
            {% if page_obj.has_previous %}
                <a href="?page=1&{{ query_params }}">首页</a>
                <a href="?page={{ page_obj.previous_page_number }}&{{ query_params }}">上一页</a>
            {% endif %}

            <span class="current">页码 {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}&{{ query_params }}">下一页</a>
                <a href="?page={{ page_obj.paginator.num_pages }}&{{ query_params }}">尾页 &raquo;</a>
            {% endif %}
        </div>
    {% endblock %}
</body>
</html>